# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('OfferType', models.CharField(choices=[('Exchange', 'Swap'), ('Purchase', 'Buy')], default='Buy', max_length=15)),
                ('BidAmount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('condition', models.CharField(choices=[('Brand new', 'New'), ('Second hand', 'Used'), ('Damaged', 'Damaged')], default='new', max_length=11)),
                ('type', models.CharField(choices=[('Academic', 'Academics'), ('Office', 'Office')], default='acads', max_length=8)),
                ('course_name', models.CharField(blank=True, max_length=25)),
                ('thumbnail', models.ImageField(blank=True, upload_to='profile_image')),
                ('tag', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('occupation', models.CharField(choices=[('Student', 'student'), ('Staff', 'staff')], default='student', max_length=7)),
                ('degree_OR_office', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.User'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketplace.Posts'),
        ),
        migrations.AddField(
            model_name='offer',
            name='post_To',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Posts'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user_Offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.User'),
        ),
    ]
