# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20170815_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='OfferStat',
            field=models.CharField(choices=[('Up', 'Up'), ('Accept', 'Accept'), ('Decline', 'Decline')], default='Up', max_length=8),
        ),
        migrations.AddField(
            model_name='offer',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
