# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_offer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='OfferStat',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Decline', 'Decline')], default='Pending', max_length=8),
        ),
    ]
