# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20170726_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default='student', max_length=7),
        ),
    ]
