# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20170727_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='condition',
            field=models.CharField(choices=[('Brand new', 'new'), ('Second hand', 'used'), ('Damaged', 'Damage')], default='new', max_length=11),
        ),
        migrations.AlterField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('Academic', 'acads'), ('Office', 'office')], default='acads', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('Student', 'student'), ('Staff', 'staff')], default='student', max_length=7),
        ),
    ]
