# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20170727_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
